
preload = /home/yvitex/.config/wallpaper/wallhaven-o5w1gl.png

wallpaper {
    monitor = 
    path = /home/yvitex/.config/wallpaper/wallhaven-o5w1gl.png
    fit_mode = cover
}

ipc = on
splash = false